### PR TITLE
Sort imports according to source module names

### PR DESCRIPTION
**Pull request by xixixao**
The test would fail before. Aligns with the way we now sort imports internally (I think this changed because of the LHS changes causing reordering of the import lines more often, also it's kinda weird if `import type X` and `import type {Y}` are mixed).

### CODE REVIEW

**Comment by kyldvs** [comment]
I hate that lint rule, sorting should be based on LHS :( do you know who owns it and if it would be possible to change? if not we can just merge this I guess..

**Comment by xixixao** [comment]
@kyldvs No clue, I couldn't find it online so I guess it's internal, will find out tomorrow.

**Comment by xixixao** [comment]
@kyldvs I say we just go with this. There is a rule that people are ok with, is consistent, and will lead to less churn in ordering. I added a test for immutable being in the right place.

**Comment by kyldvs** [comment]
Sounds good

**Pull request merged**
