### PR TITLE
Fix mixed casing

### PR DESCRIPTION
**Pull request by xixixao**
I don't think these cases are used in our codebase, but I want to make this implementation as robust as possible before I use it in the ESLint rule. You might want to review each commit separately.

### CODE REVIEW

**Comment by kyldvs** [comment]
Looks good - let me know when you think this is ready for a release. If appropriate we could also move it to a more appropriately named atom package, organize-requires?

**Comment by xixixao** [comment]
So I wanted to rename the command (to Fix Requires) but leave the package name. Even if I rename the command people will have to rebind hotkey if they have a custom one. If we rename the whole package, how much thrash is it gonna cause? Can we still auto-install it at FB?

Apart from this it's probably ready. I want to fix the internal ESLint rule using this code, but I haven't got around to that yet (not gonna happen until next week most likely).

**Comment by kyldvs** [comment]
I think it would be possible to abandon this project and create a new one with a more reasonable name and still auto-install it. @zertosh Would there be any issues doing that?

Yeah not sure how thrashy renaming the command would be

**Comment by zertosh** [comment]
@kyldvs yup - ping me over messenger

**Pull request merged**
